#!/usr/bin/env bash
# =============================================================
#   deploy_to_genesis.sh
#
#   Mac-Mini-side deploy of a freshly-trained wall-segmentation model.
#   Run this on the Mac Mini AFTER a Colab-trained `walls.onnx` is in
#   place at $1 (or at the default path).
#
#   This is the second half of the Colab + Mac split I designed:
#     Colab trains → ONNX saved here
#     Mac deploys the ONNX → live on genesis-mind.com
#
#   What it does:
#     1. Verifies the ONNX file exists and is well-formed
#     2. Verifies gh CLI auth (you'll need `gh auth login` once)
#     3. Creates or updates a GitHub Release with the ONNX attached
#     4. Updates extract-tool/detect-model.mjs to point at the new release
#     5. Commits the URL change and pushes to main
#     6. CF Pages auto-deploys on the push — site picks up the new model
#        within ~30 seconds
#
#   Usage:
#     ./deploy_to_genesis.sh path/to/walls.onnx [release-tag]
#
#   If you don't pass the path, it defaults to the latest run in
#   runs/<most-recent>/walls.onnx (the output of export_onnx.py).
# =============================================================
set -euo pipefail

REPO_ROOT="/Users/anndygarcia/genesis-v0"
ONNX_PATH="${1:-}"
RELEASE_TAG="${2:-v0.4-walls-$(date +%Y%m%d-%H%M%S)}"

cd "$REPO_ROOT"

# ----- 1. Resolve and verify ONNX -----------------------------------
if [ -z "$ONNX_PATH" ] || [ ! -f "$ONNX_PATH" ]; then
    # Try the most recent runs/<timestamp>/walls.onnx
    CANDIDATE=$(find extract-tool/train/runs -name 'walls.onnx' -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -1 | awk '{print $2}')
    if [ -z "$CANDIDATE" ] || [ ! -f "$CANDIDATE" ]; then
        echo "ERROR: no ONNX file found." >&2
        echo "Run train/src/export_onnx.py in Colab first, then either:" >&2
        echo "  scp the walls.onnx back to $REPO_ROOT/extract-tool/models/walls.onnx" >&2
        echo "  or pass the path as the first arg: $0 /path/to/walls.onnx" >&2
        exit 1
    fi
    ONNX_PATH="$CANDIDATE"
fi
echo "[deploy] using ONNX: $ONNX_PATH ($(du -h "$ONNX_PATH" | cut -f1))"

python3 -c "
import onnx
m = onnx.load('$ONNX_PATH')
print('[deploy] ONNX IR version:', m.ir_version)
print('[deploy] Inputs :', [(i.name, [d.dim_value for d in i.type.tensor_type.shape.dim]) for i in m.graph.input])
print('[deploy] Outputs:', [(o.name, [d.dim_value for d in o.type.tensor_type.shape.dim]) for o in m.graph.output])
" || { echo "ERROR: invalid ONNX file"; exit 1; }

# ----- 2. GitHub release --------------------------------------------
if ! gh auth status >/dev/null 2>&1; then
    echo "ERROR: gh CLI not authenticated. Run: gh auth login" >&2
    exit 1
fi

REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner)
echo "[deploy] pushing to $REPO as release $RELEASE_TAG"

# Create or replace the release asset
gh release create "$RELEASE_TAG" "$ONNX_PATH" \
    --repo "$REPO" \
    --title "Walls ONNX — $RELEASE_TAG" \
    --notes "Fine-tuned wall/door/window segmentation model. Drop-in replacement for v0.3-walls." \
    2>&1 | tail -3 || {
        # If the tag exists, upload as an asset to the existing release
        echo "[deploy] tag exists; uploading as replacement asset"
        gh release upload "$RELEASE_TAG" "$ONNX_PATH" --repo "$REPO" --clobber
    }

# ----- 3. Update detect-model.mjs URL -------------------------------
URL="https://github.com/anndygarcia/genesis-v0/releases/download/${RELEASE_TAG}/walls.onnx"
echo "[deploy] updating detect-model.mjs to point at $URL"

if grep -q "^const MODEL_URL_DEFAULT" extract-tool/detect-model.mjs; then
    # Replace inline.
    sed -i '' "s|^const MODEL_URL_DEFAULT = .*\$|const MODEL_URL_DEFAULT = '${URL}';|" \
        extract-tool/detect-model.mjs
else
    echo "ERROR: couldn't find MODEL_URL_DEFAULT in detect-model.mjs" >&2
    exit 1
fi

# ----- 4. Commit + push ---------------------------------------------
git add extract-tool/detect-model.mjs
if ! git diff --cached --quiet; then
    git commit -m "extract-tool: update walls.onnx to $RELEASE_TAG

Generated by Colab fine-tune, deployed via train/deploy_to_genesis.sh."
    git push origin main
    echo "[deploy] pushed."
else
    echo "[deploy] no URL change to commit."
fi

# ----- 5. Live verification helper ----------------------------------
echo "[deploy] done. CF Pages will auto-deploy in ~30s."
echo "[deploy] Live URL to verify: https://genesis-mind.com/?extract=raster-sample"
